package com.mikejhill.voxlog.core.model

import java.time.Instant

/**
 * A single journal entry.
 *
 * All timestamps are UTC [Instant]s. The only local-time value is the default [title], which is
 * rendered with the device's UTC offset at capture time (see [DefaultNoteTitle]).
 *
 * @property captureMethod how the note was created; fixed at creation and never changed.
 * @property text the editable body. For voice notes it starts as the transcript.
 * @property rawTranscript the unmodified speech-to-text output, kept even after [text] is edited.
 * @property audioFileName file name of retained audio inside the app's audio directory, or null.
 * @property durationMillis recording length for voice notes; null for text notes.
 * @property transcriptionProgressPercent 0–100 while [status] is [NoteStatus.TRANSCRIBING].
 * @property captureShortcutId id of the launcher shortcut used to create the note, if any.
 */
data class Note(
    val id: NoteId,
    val categoryId: CategoryId,
    val captureMethod: CaptureMethod,
    val title: String,
    val titleSource: TitleSource,
    val text: String,
    val rawTranscript: String?,
    val createdAt: Instant,
    val updatedAt: Instant,
    val durationMillis: Long?,
    val audioFileName: String?,
    val location: GeoLocation?,
    val language: String?,
    val status: NoteStatus,
    val transcriptionProgressPercent: Int?,
    val labelIds: Set<LabelId>,
    val captureShortcutId: String?,
    val processingLog: String?,
) {
    /** Number of whitespace-separated words in [text]. */
    val wordCount: Int
        get() = text.split(WHITESPACE).count { it.isNotBlank() }

    /** Whether retained audio exists for this note. */
    val hasAudio: Boolean
        get() = audioFileName != null

    private companion object {
        val WHITESPACE = Regex("\\s+")
    }
}

/** How a note was originally captured. */
enum class CaptureMethod {
    /** Spoken and transcribed; text is generated from audio. */
    VOICE_RECORDING,

    /** Typed directly in the composer. */
    TEXT_ENTRY,
}

/** Who produced the current note title; auto-naming may only replace [DEFAULT] titles. */
enum class TitleSource {
    /** The capture timestamp generated by [DefaultNoteTitle]. */
    DEFAULT,

    /** Typed or edited by the user; never overwritten automatically. */
    USER,

    /** Generated by post-processing. */
    AUTO,
}

/** Lifecycle of a note through the capture and processing pipeline. */
enum class NoteStatus {
    /** Audio is still being recorded. */
    RECORDING,

    /** Saved; speech-to-text is in progress. */
    TRANSCRIBING,

    /** Saved and transcribed; optional post-processing is running. */
    PROCESSING,

    /** All processing has finished. */
    READY,

    /** A processing step failed; the note itself is still saved. */
    FAILED,
}

/** Where a note was captured, when location capture is enabled. */
data class GeoLocation(val latitude: Double, val longitude: Double, val accuracyMeters: Float?, val placeName: String?)
