package com.mikejhill.voxlog.core.data.repository

import com.mikejhill.voxlog.core.model.CategoryId
import com.mikejhill.voxlog.core.model.LabelId
import com.mikejhill.voxlog.core.model.Note
import com.mikejhill.voxlog.core.model.NoteFilter
import com.mikejhill.voxlog.core.model.NoteId
import java.io.File
import kotlinx.coroutines.flow.Flow

/** Creates, reads and edits notes. All writes are local first; processing runs in the background. */
interface NoteRepository {
    /** Streams notes matching [filter], newest first. In-progress recordings are excluded. */
    fun observeNotes(filter: NoteFilter): Flow<List<Note>>

    /** Streams one note, emitting null once it no longer exists. */
    fun observeNote(id: NoteId): Flow<Note?>

    /** Returns one note, or null. */
    suspend fun getNote(id: NoteId): Note?

    /** Saves a typed note and schedules indexing; returns its id. */
    suspend fun createTextNote(draft: TextNoteDraft): NoteId

    /** The WAV file a recording for [noteId] must be written to. Callers may start recording before [beginVoiceNote]. */
    fun recordingFileFor(noteId: NoteId): File

    /**
     * Inserts a voice note in the RECORDING state, so a crash mid-recording never loses the capture.
     * The microphone should already be running; this only persists the row.
     */
    suspend fun beginVoiceNote(request: VoiceCaptureRequest)

    /**
     * Marks a recording finished and schedules transcription. If the user switched category while
     * recording, the final category's capture-time settings apply. Never blocks on processing.
     */
    suspend fun completeVoiceNote(id: NoteId, durationMillis: Long, categoryId: CategoryId)

    /** Replaces the title; marks it user-owned so auto-naming never overwrites it. */
    suspend fun updateTitle(id: NoteId, title: String)

    /** Replaces the editable text body. */
    suspend fun updateText(id: NoteId, text: String)

    /** Moves a note to another category without re-running capture-time settings. */
    suspend fun moveToCategory(id: NoteId, categoryId: CategoryId)

    /** Replaces the label set of a note. */
    suspend fun setLabels(id: NoteId, labelIds: Set<LabelId>)

    /** Permanently removes a note's retained audio; the text stays. */
    suspend fun deleteAudio(id: NoteId)

    /** Permanently deletes a note and its audio. */
    suspend fun deleteNote(id: NoteId)

    /** Re-runs post-processing for a note on demand. */
    suspend fun reprocess(id: NoteId)

    /** Returns the retained audio file of a note, if any. */
    fun audioFileFor(note: Note): File?
}

/**
 * A typed note ready to save.
 *
 * @property title the title to use, or null to use the default timestamp title.
 */
data class TextNoteDraft(
    val categoryId: CategoryId,
    val title: String?,
    val text: String,
    val labelIds: Set<LabelId> = emptySet(),
    val captureShortcutId: String? = null,
)

/** Parameters for starting a voice capture; [noteId] is generated by the caller so recording can start first. */
data class VoiceCaptureRequest(val noteId: NoteId, val categoryId: CategoryId, val captureShortcutId: String? = null)
